# Generated by Django 5.0.6 on 2024-05-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id_cinema',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_cinema',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='reservationmovie',
            name='id_movie',
        ),
        migrations.RemoveField(
            model_name='reservationmovie',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationMovie',
        ),
    ]
