# Generated by Django 5.0.4 on 2024-05-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_movie', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('duration', models.CharField(default='-', max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('poster', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movied.client')),
                ('movie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movied.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationMovie',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('num_tickets', models.IntegerField(default=None)),
                ('id_movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movied.movie')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movied.reservation')),
            ],
        ),
    ]
