# Generated by Django 5.0.4 on 2024-05-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id_cinema', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_movie', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('ranking', models.FloatField(max_length=50, null=True)),
                ('id_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movied.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('id_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movied.cinema')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movied.client')),
                ('movie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movied.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationMovie',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('num_tickets', models.IntegerField()),
                ('id_movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movied.movie')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movied.reservation')),
            ],
        ),
    ]
