# Generated by Django 5.0.4 on 2024-05-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movied', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='id_cinema',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ranking',
        ),
        migrations.AddField(
            model_name='cinema',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(max_length=500),
        ),
    ]
