# Generated by Django 5.0.6 on 2024-05-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movied', '0002_reservation_cinema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='cinema',
            new_name='cinema_id',
        ),
    ]
