# Generated by Django 5.0.4 on 2024-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movied', '0002_remove_cinema_id_cinema_remove_movie_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmovie',
            name='num_tickets',
            field=models.IntegerField(default=None),
        ),
    ]
