# Generated by Django 5.0.6 on 2024-05-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movied', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
