# Generated by Django 5.0.4 on 2024-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movied', '0002_reservation_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
