# Generated by Django 5.0.4 on 2024-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movied', '0003_alter_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
