import re
from playwright.sync_api import Page, expect


def test_4deleteMultipleReservations(page: Page) -> None:
    page.goto("http://127.0.0.1:8000/")
    page.get_by_role("link", name="Go to available cinemas").click()
    page.get_by_role("button", name="Espai Funàtic").click()
    page.get_by_role("link", name="JFK").click()
    page.get_by_label("Username:").click()
    page.get_by_label("Username:").fill("geiade")
    page.get_by_label("Password:").click()
    page.get_by_label("Password:").fill("geiadegeiade")
    page.get_by_role("button", name="Log In").click()
    page.get_by_label("Select Showtime:").click()
    page.get_by_label("Select Showtime:").select_option("20:00")
    page.get_by_label("Select tickets:").click()
    page.get_by_label("Select tickets:").fill("3")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Confirm Reservation").click()
    page.get_by_role("link", name="The Lord of the Rings: The Fellowship of the Ring").click()
    page.get_by_label("Select Showtime:").click()
    page.get_by_label("Select Showtime:").select_option("18:00")
    page.get_by_label("Select tickets:").click()
    page.get_by_label("Select tickets:").fill("5")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Confirm Reservation").click()
    page.get_by_role("link", name="No Time to Die").click()
    page.get_by_label("Select Showtime:").click()
    page.get_by_label("Select Showtime:").select_option("22:00")
    page.get_by_label("Select tickets:").click()
    page.get_by_label("Select tickets:").fill("7")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Confirm Reservation").click()
    page.get_by_role("link", name="Back", exact=True).click()
    page.get_by_role("link", name="Back").click()
    page.get_by_role("link", name="Go to my reservations").click()
    page.get_by_role("link", name="Delete").nth(4).click()
    page.get_by_role("link", name="Delete").nth(4).click()
    page.get_by_role("link", name="Delete").nth(4).click()
    page.get_by_role("link", name="Log Out").click()
