import re
from playwright.sync_api import Page, expect


def test_6editMultipleReservations(page: Page) -> None:
    page.goto("http://127.0.0.1:8000/")
    page.get_by_role("link", name="Go to available cinemas").click()
    page.get_by_role("button", name="Cinemes Lauren").click()
    page.get_by_role("link", name="Rocky").click()
    page.get_by_label("Username:").click()
    page.get_by_label("Username:").fill("geiade")
    page.get_by_label("Password:").click()
    page.get_by_label("Password:").fill("geiadegeiade")
    page.get_by_role("button", name="Log In").click()
    page.get_by_label("Select Showtime:").click()
    page.get_by_label("Select Showtime:").select_option("20:00")
    page.get_by_label("Select tickets:").click()
    page.get_by_label("Select tickets:").fill("8")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Confirm Reservation").click()
    page.get_by_role("link", name="Spider-Man: No Way Home").click()
    page.get_by_label("Select Showtime:").click()
    page.get_by_label("Select Showtime:").select_option("18:00")
    page.get_by_label("Select tickets:").click()
    page.get_by_label("Select tickets:").fill("4")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Confirm Reservation").click()
    page.get_by_role("link", name="Terminator 2: Judgment Day").click()
    page.get_by_label("Select Showtime:").click()
    page.get_by_label("Select Showtime:").select_option("20:00")
    page.get_by_label("Select tickets:").click()
    page.get_by_label("Select tickets:").fill("2")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Confirm Reservation").click()
    page.get_by_role("link", name="Back", exact=True).click()
    page.get_by_role("link", name="Back").click()
    page.get_by_role("link", name="Go to my reservations").click()
    page.get_by_role("link", name="Edit").nth(5).click()
    page.get_by_label("Showtime:").click()
    page.get_by_label("Showtime:").select_option("22:00")
    page.get_by_label("Num tickets:").click()
    page.get_by_label("Num tickets:").fill("7")
    page.get_by_role("button", name="Save changes").click()
    page.get_by_role("link", name="Edit").nth(6).click()
    page.get_by_label("Showtime:").click()
    page.get_by_label("Showtime:").select_option("20:00")
    page.get_by_role("button", name="Save changes").click()
    page.get_by_role("link", name="Edit").nth(7).click()
    page.get_by_label("Num tickets:").click()
    page.get_by_label("Num tickets:").fill("10")
    page.get_by_role("button", name="Save changes").click()
    page.get_by_role("link", name="Log Out").click()
